FROM node:22.12.0-alpine3.21 AS development

WORKDIR /app

RUN apk update && apk upgrade --no-cache && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

COPY package*.json ./

RUN npm ci && npm cache clean --force

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
